"""Fyers API v3 adapter.

Auth flow (auth_kind = "oauth_redirect"):
  1. Frontend redirects browser to
     https://api-t1.fyers.in/api/v3/generate-authcode
       ?client_id=...&redirect_uri=...&response_type=code&state=...
     (generated by `SessionModel.generate_authcode()`).
  2. Fyers redirects back with `?auth_code=XXX&state=...&s=ok`.
  3. We exchange via `SessionModel(grant_type="authorization_code",
     secret_key=API_SECRET).generate_token()` which POSTs to
     `/api/v3/validate-authcode` with
     `appIdHash = SHA256(api_key:api_secret)`.

Fyers symbol format:
  Orders require a full symbol string like `NSE:RELIANCE-EQ`, not a
  plain trading symbol. We construct it deterministically from
  (symbol, exchange) with the `-EQ` cash-equity suffix hard-coded
  since we only support cash equity (F&O is out of scope).
"""

from __future__ import annotations

from collections.abc import Mapping
from decimal import Decimal

from fyers_apiv3.fyersModel import FyersModel, SessionModel

from src.adapters.base import BrokerAdapter
from src.adapters.errors import (
    AuthError,
    BrokerError,
    InvalidOrderError,
    RateLimitError,
    TransientBrokerError,
)
from src.adapters.fyers.mapping import (
    ACTION_CODE,
    PRICE_TYPE_CODE,
    PRODUCT_CODE,
    fyers_symbol,
)
from src.config import get_settings
from src.schemas import (
    Action,
    BrokerSession,
    Exchange,
    Holding,
    OrderRequest,
    OrderResult,
)


def _classify_fyers_error(resp: dict | None, *, context: str) -> BrokerError:
    """Map Fyers JSON error responses to our error taxonomy."""
    if not isinstance(resp, dict):
        return BrokerError(f"{context}: unexpected response", broker="fyers")
    code = str(resp.get("code") or "")
    msg = f"{context}: {resp.get('message', 'unknown error')}"
    if code in {"-99", "-15"}:
        return AuthError(msg, code=code, broker="fyers")
    if code == "-429":
        return RateLimitError(msg, code=code, broker="fyers")
    if code.startswith("-5"):
        return TransientBrokerError(msg, code=code, broker="fyers")
    return InvalidOrderError(msg, code=code or None, broker="fyers")

class FyersAdapter(BrokerAdapter):
    name = "fyers"
    display_name = "Fyers"
    auth_kind = "oauth_redirect"

    def __init__(
        self,
        api_key: str | None = None,
        api_secret: str | None = None,
        redirect_uri: str | None = None,
    ) -> None:
        settings = get_settings()
        self._api_key = api_key or settings.fyers_api_key
        self._api_secret = api_secret or settings.fyers_api_secret
        self._redirect_uri = redirect_uri or (
            f"{settings.public_base_url}/auth/fyers/callback"
        )
        if not (self._api_key and self._api_secret):
            raise AuthError(
                "Fyers adapter requires FYERS_API_KEY and FYERS_API_SECRET",
                broker="fyers",
            )

    def _session_model(self, state: str = "state") -> SessionModel:
        return SessionModel(
            client_id=self._api_key,
            secret_key=self._api_secret,
            redirect_uri=self._redirect_uri,
            response_type="code",
            grant_type="authorization_code",
            state=state,
        )

    def build_login_url(self, redirect_uri: str, state: str) -> str:

        sm = self._session_model(state=state)
        return sm.generate_authcode()

    def exchange_code_for_session(self, params: Mapping[str, str]) -> BrokerSession:
        auth_code = params.get("auth_code") or params.get("code")
        if not auth_code:
            raise AuthError("Fyers callback missing auth_code", broker="fyers")
        sm = self._session_model()
        sm.set_token(auth_code)
        resp = sm.generate_token()
        if not isinstance(resp, dict) or resp.get("s") != "ok":
            raise _classify_fyers_error(resp, context="generate_token")
        return BrokerSession(
            broker="fyers",
            access_token=resp["access_token"],
            token_header_format="{app_id}:{access_token}",
            refresh_token=resp.get("refresh_token"),
            extras={"app_id": self._api_key},
        )

    def authorization_header(self, session: BrokerSession) -> dict[str, str]:
        app_id = session.extras.get("app_id", self._api_key)
        return {
            "Authorization": session.token_header_format.format(
                app_id=app_id, access_token=session.access_token
            ),
            "Accept": "application/json",
            "Content-Type": "application/json",
        }

    def _client(self, session: BrokerSession) -> FyersModel:
        return FyersModel(
            client_id=self._api_key,
            token=session.access_token,
            log_path="",
        )

    def place_order(self, session: BrokerSession, req: OrderRequest) -> OrderResult:
        client = self._client(session)
        data = {
            "symbol": fyers_symbol(req.symbol, req.exchange),
            "qty": req.quantity,
            "type": PRICE_TYPE_CODE[req.price_type],
            "side": ACTION_CODE[req.action],
            "productType": PRODUCT_CODE[req.product],
            "limitPrice": float(req.price) if req.price is not None else 0,

            "stopPrice": 0,
            "validity": "DAY",
            "disclosedQty": 0,

            "offlineOrder": req.amo,
        }
        resp = client.place_order(data=data)
        if not isinstance(resp, dict):
            return OrderResult.failed(
                req, code="FYERS_BAD_RESP", message=str(resp)[:200]
            )
        if resp.get("s") != "ok":
            err = _classify_fyers_error(resp, context="place_order")
            if isinstance(err, InvalidOrderError):
                return OrderResult.failed(
                    req, code=err.code or "FYERS_REJECTED", message=str(err)
                )
            raise err
        order_id = resp.get("id") or resp.get("orderNumStatus") or ""
        return OrderResult.placed(req, broker_order_id=str(order_id))

    def cancel_order(self, session: BrokerSession, broker_order_id: str) -> None:
        client = self._client(session)
        resp = client.cancel_order(data={"id": broker_order_id})
        if not isinstance(resp, dict) or resp.get("s") != "ok":
            raise _classify_fyers_error(resp, context="cancel_order")

    def get_order_status(
        self, session: BrokerSession, broker_order_id: str
    ) -> OrderResult:
        client = self._client(session)
        resp = client.orderhistory(data={"id": broker_order_id})
        if not isinstance(resp, dict) or resp.get("s") != "ok":
            raise _classify_fyers_error(resp, context="orderhistory")
        history = resp.get("orderBook") or resp.get("data") or []
        if not history:
            raise BrokerError(
                f"No history for order_id={broker_order_id}", broker="fyers"
            )
        latest = history[-1]
        raw_symbol = latest.get("symbol", "")
        parsed_symbol = raw_symbol.split(":", 1)[-1].replace("-EQ", "") or "UNKNOWN"
        req = OrderRequest(
            symbol=parsed_symbol,
            exchange=Exchange.NSE
            if raw_symbol.startswith("NSE")
            else Exchange.BSE,
            action=Action.BUY if latest.get("side", 1) == 1 else Action.SELL,
            quantity=int(latest.get("qty", 0)) or 1,
        )
        status = int(latest.get("status", 0))

        if status in {1, 5}:
            return OrderResult.failed(
                req,
                code=f"FYERS_STATUS_{status}",
                message=latest.get("message", f"status={status}"),
            )
        return OrderResult.placed(req, broker_order_id=broker_order_id)

    def get_holdings(self, session: BrokerSession) -> list[Holding]:
        client = self._client(session)
        resp = client.holdings()
        if not isinstance(resp, dict) or resp.get("s") != "ok":
            raise _classify_fyers_error(resp, context="holdings")
        out: list[Holding] = []
        for row in resp.get("holdings", []):
            qty = int(row.get("quantity", 0) or 0)
            if qty <= 0:
                continue
            fyers_symbol = row.get("symbol", "") or ""
            parsed_symbol = (
                fyers_symbol.split(":", 1)[-1].replace("-EQ", "") if fyers_symbol else ""
            )
            out.append(
                Holding(
                    symbol=parsed_symbol or row.get("symbolName", ""),
                    exchange=Exchange.NSE
                    if fyers_symbol.startswith("NSE")
                    else Exchange.BSE,
                    quantity=qty,
                    average_price=Decimal(str(row["costPrice"]))
                    if row.get("costPrice") is not None
                    else None,
                )
            )
        return out
